# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :linux => {
        :box_name => "centos/7",
	:disks => {
		
		:sata2 => {
                        :dfile => './sata2.vdi',
                        :size => 2048, # Megabytes
						:port => 2
		}
	}
  },
}

Vagrant.configure("2") do |config| 

  MACHINES.each do |boxname, boxconfig| 

      config.vm.define boxname do |box| 

          box.vm.box = boxconfig[:box_name] 
          
          box.vm.provider :virtualbox do |vb| 
            	  vb.customize ["modifyvm", :id, "--memory", "1024"] 
                  needsController = false 
		  boxconfig[:disks].each do |dname, dconf| 
			  unless File.exist?(dconf[:dfile]) 
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true 
                          end
		  end
                  if needsController == true 
                     vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL 

cat > /etc/sysconfig/watchlog <<EOF
# Configuration file for my watchdog service
# Place it to /etc/sysconfig
# File and word in that file that we will be monit
WORD="ALERT"
LOG=/var/log/watchlog.log
EOF

cat > /opt/watchlog.sh <<EOF
#!/bin/bash
WORD=\\$1
LOG=\\$2
DATE=\\`date\\`
if grep \\$WORD \\$LOG &> /dev/null
then
logger "\\$DATE: I found word, Master!"
else
exit 0
fi
EOF
chmod +x /opt/watchlog.sh


cat > /usr/lib/systemd/system/watchlog.service <<EOF
[Unit]
Description=My watchlog service

[Service]
Type=oneshot
EnvironmentFile=/etc/sysconfig/watchlog
ExecStart=/opt/watchlog.sh \\$WORD \\$LOG
EOF

cat > /usr/lib/systemd/system/watchlog.timer <<EOF
[Unit]
Description=Run watchlog script every 30 second
[Timer]
# Run every 30 second
OnUnitActiveSec=30
Unit=watchlog.service
[Install]
WantedBy=multi-user.target
EOF

cat > /var/log/watchlog.log <<LOG
-------
sdgsdfpodg ALERT
908868t7yul'kln ALERT
gfdhgpgfokhpogf
vcbcbvvbALERT
sdgffdgALERTrgfdgfdg
--------
LOG

systemctl start watchlog.timer
tail /var/log/messages

	  SHELL
      end
  end
end
